### ISSUE TITLE
Possible to front end rtorrent-rutorrent with this container?

### ISSUE THREAD

**Issue by joshuajbrunner** [xataz/docker-reverse-nginx#10]
Hi there,

I've been trying to get a nginx reverse proxy working with docker containers that have rutorrent/nginx built in. 

I've been messing around with your docker-rtorrent-rutorrent container (https://github.com/xataz/docker-rtorrent-rutorrent) with the container working locallly on http://debian.local:9080/rutorrent

Now I'd like to be able to be able to remove  the port so the request URL just looks like http://debian.local/rutorrent so I can run multiple instances with different locations ie /rutorrent1, /rutorrent2, /rutorrent3, etc...

I've been messing around with this container for a bit and can't seem to get it to work natively.

Here's what I'm running

```
docker run -dt \
    -p 6881:6881 \
    -p 6881:6881/udp \
    --net="rtorrent" \
    --name=rutorrent \
    --hostname=rutorrent \
    --net-alias=rutorrent \
    --label reverse.frontend.domain=debian.local \
    --label reverse.frontend.path="/rutorrent" \
    --label reverse.backend.port=9080 \
    -e WEBROOT=/rutorrent \
    -e DHT_RTORRENT=on \
    -e PORT_RTORRENT=6881  \
    -e UID=1001 \
    -e GID=1001 \
    -v rutorrent-data-volume:/data \
    -v /docker/config:/config \
    xataz/rtorrent-rutorrent
```

```
docker run -d \
	-p 80:8080 \
	-p 443:8443 \
    --name reverse \
    --net="rtorrent" \
    --hostname=reverse \
    --net-alias=reverse \
    -v /var/run/docker.sock:/var/run/docker.sock \
	xataz/reverse-nginx
```

Note: If in my rutorrent container I specify "rutorrent" as the label.reverse.frontend.path value, I get a 404 not found when navigating to http://debian.local/rutorrent
If I specify "/rutorrent" I get a 502 Bad Gateway page

Also the net/hostname/net-alias stuff is to get the containers talking to each other on the "rtorrent" network I set up. Otherwise the docker-reverse-nginx container doesn't find rutorrent container.

Any ideas to get this working?

Thanks much!

**Comment by xataz** [comment]
Hi,

I have the same problem, but if use https://mydomain.org/rutorrent/ (end with **/**).

After check rutorrent sources, it create a redirection based on location header for add / after URL, but it keeps the original port (8080).

**Comment by joshuajbrunner** [comment]
@xataz Thank you. I actually got it to work in the same manner you described with the jwilder/nginx-proxy container. http://mydomain.org/rutorrent/ works but http://mydomain.org/rutorrent (no trailing slash) does not work and instead redirects to http://mydomain.org:8080/rutorrent/

I had this issue with the Flood UI too and specifying port_in_redirect off; in the server block worked for that but its not working here.

Anyways, here is what I ran to get it working.

```
docker run -dt \
-p 51000:51000 \
-p 51000:51000/udp \
--net="rtorrent" \
--name=rutorrent \
--hostname=rutorrent \
--net-alias=rutorrent \
-e WEBROOT=/rutorrent \
-e DHT_RTORRENT=on \
-e PORT_RTORRENT=6881  \
-e UID=1001 \
-e GID=1001 \
-v rutorrent-data-volume:/data \
-v /docker/config:/config \
xataz/rtorrent-rutorrent
```

```
docker run -d -p 80:80 -p 443:443 \
    --name nginx-proxy \
    --net="rtorrent" \
    --hostname=nginx-proxy \
    --net-alias=nginx-proxy \
    -v /home/nobody/Docker/nginx-proxy/nginx/conf.d:/etc/nginx/conf.d \
    -v /home/nobody/Docker/nginx-proxy/nginx/logs:/var/log/nginx \
    -v /home/nobody/Docker/nginx-proxy/nginx/vhost.d:/etc/nginx/vhost.d \
    -v /var/run/docker.sock:/tmp/docker.sock:ro \
    jwilder/nginx-proxy
```

And in /etc/nginx/conf.d folder in the nginx-proxy container, create a file with your virtual host (ie debian.local.conf). Server IP in upstream is the IP address of the container.

```
# debian
upstream debian{
                                ## Can be connect with "rtorrent" network
                        # rutorrent
                        server 172.18.0.2:8080;
}
server {
        server_name debian.local;
        listen 80;
        access_log /var/log/nginx/access.log vhost;

        port_in_redirect off;

        location /rutorrent {
            proxy_pass http://debian;
            proxy_redirect off;
        }
}
```

Gonna close this issue out. Maybe I'll try to get it working eventually so that I don't need the trailing slash.

**Comment by joshuajbrunner** [comment]
@xataz 

I might have found the solution. In conjunction with my above config, add in the following to the nginx.conf (/etc/nginx/nginx.conf) in your rutorrent-rtorrent container in the server block

`absolute_redirect off;`

So it should look something like this 
```
...
    error_page 500 502 503 504 /50x.html;
    location = /50x.html { root /usr/share/nginx/html; }
    root /var/www/html;

    absolute_redirect off;

    location = /favicon.ico {
        access_log off;
        log_not_found off;
    }

    location ^~ /rutorrent {
        root /var/www/html;
        location ~ \.php$ {
...
```

This seems to be working for me. 

Regards~
