### ISSUE TITLE
Mise à jours des certificats impossible

### ISSUE THREAD

**Issue by Hydrog3n** [xataz/docker-reverse-nginx#14]
Salut, 
Quand le container ce lance il lance le regen des certificats mais j'ai cette erreurs sur certain 

```
error presenting token: could not start HTTPS server for challenge -> listen tcp :443: bind: permission denied
```

J'ai pas trouvé de où ça pouvais venir.

**Comment by xataz** [comment]
Salut,

Désolé je viens de voir le message, et j'ai eu le problème sur un de mes certificats aujourd'hui.
L'erreur est logique, mais ne devrait pas arriver, en gros lego tente d'écouter le port 443 (dans le conteneur), mais puisqu'il n'est pas exécuté en root, il n'a pas le droit.
Surement une modif au niveau de Lego (option qui à changé ou autre), et il ne prends plus l'option pour changer le port d'écoute avec SSL.

Je regarde de plus prêt ce soir

**Comment by Hydrog3n** [comment]
Pas de soucis pour le moment, j'ai pas de services critiques en carafe :D

**Comment by xataz** [comment]
Normalement c'est bon, en tout cas pour moi ça a marché

**Comment by Hydrog3n** [comment]
Ca fonctionne chez moi :) Merci 👍 

Tu as pu regarder l'issue #13 ?

**Comment by xataz** [comment]
Parfait je clos cette issue

Pour la #13, j'ai vu le truc qui cloche, je modifie au plus vite
