### ISSUE TITLE
Pouvoir juste utiliser le renouvellement des certifs (et planifier leurs emplacements)

### ISSUE THREAD

**Issue by Technowix** [xataz/docker-reverse-nginx#3]
Grosso modo j'aimerais bien rester maitre de mes blocks (avec le /nginx/custom_sites par exemple) mais profiter du renouvellement des certificats que propose le petit lego et la légèreté de ton container :)

J'sais pas si c'est possible dans l'état actuel.

**Comment by xataz** [comment]
Si tu veux renouveller tes certificats automatiquement, il te suffit de les mettres dans /nginx/ssl, il les renouvellera automatiquement, enfin si dans le custom site tu mets bien la location /.well-known/acme-challenge.

Après seulement gérer les certificats, c'est pas le but du conteneur malheureseument.

Autrement, je suis en train d'ajouter une fonction, qui permettra de créer des templates de configuration nginx custom.

**Comment by Technowix** [comment]
J't'avouerais m'être habitué au challenge DNS mais ça peut marcher aussi.
Du coup j'ai juste à générer à la main les certificats (à l'aide du conteneur ofc) et ce il les mettra à jour ?
J'veux dire, il m'embêtera pas avec un bloc fait maisons tant que je met pas de labels et il mettra bien à jour les certif et redémarrera nginx tout bien à chaque mises à jour de ces derniers ? x)

Si oui, c'est parfait ^-^ !

**Comment by xataz** [comment]
Oui, il touche pas à ce qu'il y a dans custom_sites.
Par contre il faut absolument mettre la location /.well-known/acme-challenge, car une fois nginx démarré, lego s'utilise en webroot et non en directe.
