### ISSUE TITLE
Création d'un dossier deux fois...

### ISSUE THREAD

**Issue by Rathorian** [xataz/docker-reverse-nginx#6]
Salut,

Je pense qu'il y a une petite coquille, il y aurait il pas deux fois la création du dossier "/nginx/sites-enabled" sur cette ligne ?

https://github.com/xataz/docker-reverse-nginx/blob/ed82fe2a08b958e2a762162980b66ecbbf2212a3/rootfs/usr/local/bin/startup#L32

**Comment by xataz** [comment]
salut,

Ah oui, bon rien de méchant, je corrige ça demain.

**Comment by Rathorian** [comment]
Oui, rien de méchant mais je voulais quand même remonter l'info.
J'aurais peut-être du créer directement un PR.
