### ISSUE TITLE
MAJ Auto des reverse

### ISSUE THREAD

**Issue by PixiBixi** [xataz/docker-reverse-nginx#8]
Plop

Le titre n'est pas très compréhensible, donc je vais essayer de l'être ici :p 

Avant de passer sous ton image reverse-proxy qui est très sympa, je fais quelques tests

  * J'ai donc fais une stack basique ruTorrent + Ton reverse proxy, tout va bien ok problème
  * J'ai voulu rajouter un nouveau container et le proxyfier via ton container, et il m'a semblé que celui-ci n'a pas généré automatiquement la conf de mon nouveau container, est-ce le cas ?

++ Un bug que je viens de m'apercevoir

J'ai modifié le _reverse.backend.port_ et je viens de m'apercevoir que le port n'a pas changé le fichier de conf, c'est problématique :p 

A+ passe sur le Slack si tu veux en parler o/

**Comment by xataz** [comment]
Salut,

Au niveau de tes UID et GID, ce sont bien les mêmes que ton user docker sur la machine hote ?

**Comment by PixiBixi** [comment]
Je t'avoue que j'ai même pas fais gaffe... Je vais regarder en rentrant du taff :D

**Comment by PixiBixi** [comment]
Carrément zapper et je suis passer sur traefik

**Comment by xataz** [comment]
Je clos donc, normalement tout ça c'est bon.
